services:
    app:
        build:
            context: ./app
        ports:
            - 3000:3000
        volumes:
            - '/home/testing:/home/dapa/testing'

    nginx:
        build:
            context: ./nginx
        ports:
            - '80:80'
        depends_on:
            - 'app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'


